#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>


unsigned int fuSeBMC_category = 2 ;
char * fuSeBMC_run_id = "kwMZsjuCfgcHvgnceEnOiuAKr";
void fuseGoalCalled(unsigned long int goal)
{
			
	FILE * fPtr = fopen("./goals_c.txt", "a");
	if(fPtr == NULL)
	{
	   printf("Error: cannot read file:%s\n" , "./goals_c.txt");
	   return;

	}
	fprintf(fPtr,"%lu\n",goal);
	fclose(fPtr);
}
int idx = -1;
int inps[17] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
_Bool __VERIFIER_nondet_bool(void)
{
	//idx++;
	//return (_Bool)inps[idx];
	return (_Bool)0;
}
char __VERIFIER_nondet_char(void)
{
	//idx++;
	//return (char)inps[idx];
	return (char)0;
}


void FuSeBMC_custom_func(void){}
extern void abort(void);
extern void __assert_fail(const char *, const char *, unsigned int, const char *) __attribute__ ((__nothrow__ , __leaf__)) __attribute__ ((__noreturn__));
void reach_error() { __assert_fail("0", "pals_lcr.4.ufo.BOUNDED-8.pals.c", 3, "reach_error"); 
fuseGoalCalled(1);
}

// This file is part of the SV-Benchmarks collection of verification tasks:
// https://github.com/sosy-lab/sv-benchmarks
//
// SPDX-FileCopyrightText: 2013 Carnegie Mellon University
// SPDX-FileCopyrightText: 2014-2020 The SV-Benchmarks Community
//
// SPDX-License-Identifier: LicenseRef-BSD-3-Clause-Attribution-CMU

/* Generated by CIL v. 1.6.0 */
/* print_CIL_Input is true */


void assert(_Bool arg ) ;
void abort(void);
typedef char msg_t;
typedef int port_t;
extern void read(port_t p , msg_t m ) ;
extern void write(port_t p , msg_t m ) ;
msg_t nomsg  =    (msg_t )-1;
char r1  ;
port_t p1  ;
char p1_old ;
char p1_new ;
char id1  ;
char st1  ;
msg_t send1  ;
_Bool mode1  ;
port_t p2  ;
char p2_old ;
char p2_new ;
char id2  ;
char st2  ;
msg_t send2  ;
_Bool mode2  ;
port_t p3  ;
char p3_old ;
char p3_new ;
char id3  ;
char st3  ;
msg_t send3  ;
_Bool mode3  ;
port_t p4  ;
char p4_old ;
char p4_new ;
char id4  ;
char st4  ;
msg_t send4  ;
_Bool mode4  ;
void node1(void) 
{ 
  msg_t m1 ;

  {
  m1 = nomsg;
  if (mode1) {
fuseGoalCalled(3);

    r1 = (char )((int )r1 + 1);
    m1 = p4_old;
    p4_old = nomsg;
    if ((int )m1 != (int )nomsg) {
      if ((int )m1 > (int )id1) {
fuseGoalCalled(6);

        send1 = m1;
      } else
{

      if ((int )m1 == (int )id1) {
fuseGoalCalled(7);

        st1 = (char)1;
      }
else
{
fuseGoalCalled(8);
}
}

    }
else
{
fuseGoalCalled(5);
}
    mode1 = (_Bool)0;
  } else {
fuseGoalCalled(4);

    p1_new = send1 != nomsg && p1_new == nomsg ? send1 : p1_new;
    mode1 = (_Bool)1;
  }
  return;
}

fuseGoalCalled(2);
}
void node2(void) 
{ 
  msg_t m2 ;

  {
  m2 = nomsg;
  if (mode2) {
fuseGoalCalled(10);

    m2 = p1_old;
    p1_old = nomsg;
    if ((int )m2 != (int )nomsg) {
      if ((int )m2 > (int )id2) {
fuseGoalCalled(13);

        send2 = m2;
      } else
{

      if ((int )m2 == (int )id2) {
fuseGoalCalled(14);

        st2 = (char)1;
      }
else
{
fuseGoalCalled(15);
}
}

    }
else
{
fuseGoalCalled(12);
}
    mode2 = (_Bool)0;
  } else {
fuseGoalCalled(11);

    p2_new = send2 != nomsg && p2_new == nomsg ? send2 : p2_new;
    mode2 = (_Bool)1;
  }
  return;
}

fuseGoalCalled(9);
}
void node3(void) 
{ 
  msg_t m3 ;

  {
  m3 = nomsg;
  if (mode3) {
fuseGoalCalled(17);

    m3 = p2_old;
    p2_old = nomsg;
    if ((int )m3 != (int )nomsg) {
      if ((int )m3 > (int )id3) {
fuseGoalCalled(20);

        send3 = m3;
      } else
{

      if ((int )m3 == (int )id3) {
fuseGoalCalled(21);

        st3 = (char)1;
      }
else
{
fuseGoalCalled(22);
}
}

    }
else
{
fuseGoalCalled(19);
}
    mode3 = (_Bool)0;
  } else {
fuseGoalCalled(18);

    p3_new = send3 != nomsg && p3_new == nomsg ? send3 : p3_new;
    mode3 = (_Bool)1;
  }
  return;
}

fuseGoalCalled(16);
}
void node4(void) 
{ 
  msg_t m4 ;

  {
  m4 = nomsg;
  if (mode4) {
fuseGoalCalled(24);

    m4 = p3_old;
    p3_old = nomsg;
    if ((int )m4 != (int )nomsg) {
      if ((int )m4 > (int )id4) {
fuseGoalCalled(27);

        send4 = m4;
      } else
{

      if ((int )m4 == (int )id4) {
fuseGoalCalled(28);

        st4 = (char)1;
      }
else
{
fuseGoalCalled(29);
}
}

    }
else
{
fuseGoalCalled(26);
}
    mode4 = (_Bool)0;
  } else {
fuseGoalCalled(25);

    p4_new = send4 != nomsg && p4_new == nomsg ? send4 : p4_new;
    mode4 = (_Bool)1;
  }
  return;
}

fuseGoalCalled(23);
}
int init(void) 
{ 
  int tmp ;

  {
  if ((int )r1 == 0) {
    if ((int )id1 >= 0) {
      if ((int )st1 == 0) {
        if ((int )send1 == (int )id1) {
          if ((int )mode1 == 0) {
            if ((int )id2 >= 0) {
              if ((int )st2 == 0) {
                if ((int )send2 == (int )id2) {
                  if ((int )mode2 == 0) {
                    if ((int )id3 >= 0) {
                      if ((int )st3 == 0) {
                        if ((int )send3 == (int )id3) {
                          if ((int )mode3 == 0) {
                            if ((int )id4 >= 0) {
                              if ((int )st4 == 0) {
                                if ((int )send4 == (int )id4) {
                                  if ((int )mode4 == 0) {
                                    if ((int )id1 != (int )id2) {
                                      if ((int )id1 != (int )id3) {
                                        if ((int )id1 != (int )id4) {
                                          if ((int )id2 != (int )id3) {
                                            if ((int )id2 != (int )id4) {
                                              if ((int )id3 != (int )id4) {
fuseGoalCalled(53);

                                                tmp = 1;
                                              } else {
fuseGoalCalled(54);

                                                tmp = 0;
                                              }
                                            } else {
fuseGoalCalled(52);

                                              tmp = 0;
                                            }
                                          } else {
fuseGoalCalled(51);

                                            tmp = 0;
                                          }
                                        } else {
fuseGoalCalled(50);

                                          tmp = 0;
                                        }
                                      } else {
fuseGoalCalled(49);

                                        tmp = 0;
                                      }
                                    } else {
fuseGoalCalled(48);

                                      tmp = 0;
                                    }
                                  } else {
fuseGoalCalled(47);

                                    tmp = 0;
                                  }
                                } else {
fuseGoalCalled(46);

                                  tmp = 0;
                                }
                              } else {
fuseGoalCalled(45);

                                tmp = 0;
                              }
                            } else {
fuseGoalCalled(44);

                              tmp = 0;
                            }
                          } else {
fuseGoalCalled(43);

                            tmp = 0;
                          }
                        } else {
fuseGoalCalled(42);

                          tmp = 0;
                        }
                      } else {
fuseGoalCalled(41);

                        tmp = 0;
                      }
                    } else {
fuseGoalCalled(40);

                      tmp = 0;
                    }
                  } else {
fuseGoalCalled(39);

                    tmp = 0;
                  }
                } else {
fuseGoalCalled(38);

                  tmp = 0;
                }
              } else {
fuseGoalCalled(37);

                tmp = 0;
              }
            } else {
fuseGoalCalled(36);

              tmp = 0;
            }
          } else {
fuseGoalCalled(35);

            tmp = 0;
          }
        } else {
fuseGoalCalled(34);

          tmp = 0;
        }
      } else {
fuseGoalCalled(33);

        tmp = 0;
      }
    } else {
fuseGoalCalled(32);

      tmp = 0;
    }
  } else {
fuseGoalCalled(31);

    tmp = 0;
  }
  return (tmp);
}

fuseGoalCalled(30);
}
int check(void) 
{ 
  int tmp ;

  {
  if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 <= 1) {
    if ((int )r1 >= 4) {
fuseGoalCalled(57);

      goto _L;
    } else
{

    if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 == 0) {
fuseGoalCalled(58);

      _L: /* CIL Label */ 
      if ((int )r1 < 4) {
fuseGoalCalled(60);

        tmp = 1;
      } else
{

      if ((((int )st1 + (int )st2) + (int )st3) + (int )st4 == 1) {
fuseGoalCalled(61);

        tmp = 1;
      } else {
fuseGoalCalled(62);

        tmp = 0;
      }
}

    } else {
fuseGoalCalled(59);

      tmp = 0;
    }
}

  } else {
fuseGoalCalled(56);

    tmp = 0;
  }
  return (tmp);
}

fuseGoalCalled(55);
}
int main(void) 
{ 
  int c1 ;
  int i2 ;

  {
  c1 = 0;
  r1 = __VERIFIER_nondet_char();
  id1 = __VERIFIER_nondet_char();
  st1 = __VERIFIER_nondet_char();
  send1 = __VERIFIER_nondet_char();
  mode1 = __VERIFIER_nondet_bool();
  id2 = __VERIFIER_nondet_char();
  st2 = __VERIFIER_nondet_char();
  send2 = __VERIFIER_nondet_char();
  mode2 = __VERIFIER_nondet_bool();
  id3 = __VERIFIER_nondet_char();
  st3 = __VERIFIER_nondet_char();
  send3 = __VERIFIER_nondet_char();
  mode3 = __VERIFIER_nondet_bool();
  id4 = __VERIFIER_nondet_char();
  st4 = __VERIFIER_nondet_char();
  send4 = __VERIFIER_nondet_char();
  mode4 = __VERIFIER_nondet_bool();
  i2 = init();
  if(!(i2))
  {
	  fuseGoalCalled(64);
	  printf("We are Abort\n");
	  abort();
  }
else
{
fuseGoalCalled(65);
}
  p1_old = nomsg;
  p1_new = nomsg;
  p2_old = nomsg;
  p2_new = nomsg;
  p3_old = nomsg;
  p3_new = nomsg;
  p4_old = nomsg;
  p4_new = nomsg;
  i2 = 0;
  while (i2 < 8) {
fuseGoalCalled(66);

    {
    node1();
    node2();
    node3();
    node4();
    p1_old = p1_new;
    p1_new = nomsg;
    p2_old = p2_new;
    p2_new = nomsg;
    p3_old = p3_new;
    p3_new = nomsg;
    p4_old = p4_new;
    p4_new = nomsg;
    c1 = check();
    assert(c1);
    i2 ++;
    }
  }
fuseGoalCalled(67);

}

fuseGoalCalled(63);
return 0;
}
void assert(_Bool arg ) 
{ 
  {
  if (! arg) {
fuseGoalCalled(69);

    {
    ERROR: 
	{
		printf("We Are in Error \n");
		reach_error();
		abort();
	}
    }
  }
else
{
fuseGoalCalled(70);
}
}

fuseGoalCalled(68);
}
