import os
import sys

from fusebmc_util.goalsorting import GoalSorting

ESBMC_EXE = './FuSeBMC_engines/ESBMC/esbmc '

SHOW_ME_OUTPUT =  True
IS_DEBUG = True

MAX_NUM_OF_LINES_OUT = 50
MAX_NUM_OF_LINES_ERRS = 50

IS_TIME_OUT_ENABLED = True
MUST_COMPILE_INSTRUMENTED = False

MUST_GENERATE_RANDOM_TESTCASE = True
MUST_ADD_EXTRA_TESTCASE = True

MUST_APPLY_TIME_PER_GOAL = True
MUST_APPLY_LIGHT_INSTRUMENT_FOR_BIG_FILES = not True

MEM_LIMIT_BRANCHES_ESBMC = 10 # giga ; Zero or negative means unlimited. 
MEM_LIMIT_BRANCHES_MAP2CHECK = 1000 # miga

MEM_LIMIT_ERROR_CALL_ESBMC = 10
MEM_LIMIT_ERROR_CALL_MAP2CHECK = 1000 # miga
MEM_LIMIT_MEM_OVERFLOW_REACH_TERM_MAP2CHECK = 1000 # miga

MEM_LIMIT_ESBMC = 10 # GiGA: Memory limit for other properties.

#MAX_VIRTUAL_MEMORY = 8 #GIGA

BIG_FILE_LINES_COUNT = 8000

AFL_HOME_PATH = os.path.abspath('./FuSeBMC_engines/AFL/')

#MAP2CHECK_EXE = os.path.abspath('./map2check/map2check ')
MAP2CHECK_EXE = os.path.abspath('./map2check-fuzzer/map2check ')
#MAP2CHECK_TIMEOUT= 150 #seconds
MAP2CHECK_ERRORCALL_SYMEX_TIMEOUT = 40 #seconds
MAP2CHECK_ERRORCALL_FUZZER_TIMEOUT = 150 #seconds

MAP2CHECK_ERRORCALL_SYMEX_ENABLED = False
MAP2CHECK_ERRORCALL_FUZZER_ENABLED = False

MAP2CHECK_COVERBRANCHES_ENABLED = not True 
MAP2CHECK_COVERBRANCHES_TIMEOUT = 70 #seconds

MAP2CHECK_MEM_OVERFLOW_REACH_TERM_ENABLED = True
MAP2CHECK_MEM_OVERFLOW_REACH_TERM_FUZZER_TIMEOUT = 150 #seconds


FUSEBMC_INSTRUMENT_EXE_PATH = os.path.abspath('./FuSeBMC_instrument/FuSeBMC_instrument')

C_COMPILER = 'gcc'

RUN_TESTCOV =  True


ERRORCALL_RUNTWICE_ENABLED = True

#for ESBMC, Fuzzer and SeedGen.
ERRORCALL_HANDLE_INFINITE_WHILE_LOOP_ENABLED = True
#ERRORCALL_INFINITE_WHILE_LOOP_LIMIT = 20
ERRORCALL_ESBMC_RUN1_TIMEOUT = 60 # seconds timeout for light ESBMC

#for ESBMC, Fuzzer and Tracer.
COVERBRANCHES_HANDLE_INFINITE_WHILE_LOOP_ENABLED = True
#COVERBRANCHES_INFINITE_WHILE_LOOP_LIMIT = 20

COVERBRANCHES_HANDLE_REPEATED_TESTCASES_ENABLED =  True

MEM_OVERFLOW_REACH_TERM_RUNTWICE_ENABLED = True


FuSeBMC_GoalTracer_ENABLED =  True
FuSeBMC_GoalTracer_CC = 'gcc' 
FuSeBMC_GoalTracer_CC_PARAMS = ''
FuSeBMC_GoalTracer_MEM_LIMIT = 5 # Giga

FuSeBMCFuzzerLib_ERRORCALL_ENABLED = True
FuSeBMCFuzzerLib_ERRORCALL_USE_SEED_FROM_ESBMC1 = True
FuSeBMCFuzzerLib_ERRORCALL_RUN2_ENABLED = True and FuSeBMCFuzzerLib_ERRORCALL_ENABLED
#FuSeBMCFuzzerLib_ERRORCALL_FORCE_RUN2 : run Fuzzer2 ignoring result from Fuzzer1
FuSeBMCFuzzerLib_ERRORCALL_FORCE_RUN2 = False and FuSeBMCFuzzerLib_ERRORCALL_RUN2_ENABLED
FuSeBMCFuzzerLib_ERRORCALL_TIMEOUT = 500 # second
FuSeBMCFuzzerLib_ERRORCALL_SEED_EXPAND_MAX_SIZE = 256 # 0  is disabled


#FuSeBMCFuzzerLib_ERRORCALL_CC = AFL_HOME_PATH+ '/afl-gcc'
FuSeBMCFuzzerLib_ERRORCALL_CC = AFL_HOME_PATH+ '/afl-gcc'
FuSeBMCFuzzerLib_ERRORCALL_CC_PARAMS = ''
FuSeBMCFuzzerLib_ERRORCALL_SELECTIVE_INPUTS_ENABLED = True
FuSeBMCFuzzerLib_ERRORCALL_SELECTIVE_INPUTS_ITERATIONS = 500

FuSeBMCFuzzerLib_ERRORCALL_SEEDGEN_CC = 'gcc'
FuSeBMCFuzzerLib_ERRORCALL_SEEDGEN_CC_PARAMS = FuSeBMCFuzzerLib_ERRORCALL_CC_PARAMS
FuSeBMCFuzzerLib_ERRORCALL_SEEDGEN_SEEDS_NUM = 1 # Number of seeds to be generated
FuSeBMCFuzzerLib_ERRORCALL_SEEDGEN_MEM_LIMIT = 5 # Giga

FuSeBMCFuzzerLib_ERRORCALL_FUSEBMC_STAGE_ITERATION_INFINITE_WHILE = 100
#FuSeBMCFuzzerLib_ERRORCALL_FUSEBMC_STAGE_ITERATION_NON_INFINITE_WHILE = 2
FuSeBMCFuzzerLib_ERRORCALL_EXTRACT_SINGLEVAL_MAXLEN_FROM_TC = True
#SF = Selective Fuzzer
FuSeBMCFuzzerLib_ERRORCALL_FUSEBMC_SF_STAGE_ITERATION = 3
FuSeBMCFuzzerLib_ERRORCALL_FUZZED_APP_TIMEOUT = '120000+' # string; millisecond;+ means tolerence
FuSeBMCFuzzerLib_ERRORCALL_FUZZED_APP_MEM_LIMIT = '5G' # string

FuSeBMCFuzzerLib_ERRORCALL_INFINITE_WHILE_TIME_INCREMENT = 10 #seconds
FuSeBMCFuzzerLib_ERRORCALL_SELECTIVE_INPUTS_TIME_INCREMENT = 20 #seconds

################## COVER-BRANCHES ###############################


FuSeBMCFuzzerLib_COVERBRANCHES_ENABLED = True
FuSeBMCFuzzerLib_COVERBRANCHES_RUN2_ENABLED = True and FuSeBMCFuzzerLib_COVERBRANCHES_ENABLED
FuSeBMCFuzzerLib_COVERBRANCHES_GLOBAL_DEPTH = True
FuSeBMCFuzzerLib_COVERBRANCHES_TIMEOUT = 600 # second
FuSeBMCFuzzerLib_COVERBRANCHES_SEED_EXPAND_MAX_SIZE = 256 # 0  is disabled



#FuSeBMCFuzzerLib_COVERBRANCHES_NUM_OF_GENERATED_TESTCASES = 0 #Don't change it; The number og generated testcases from cover-Branches.We have lstFuzzerSeeds
FuSeBMCFuzzerLib_COVERBRANCHES_NUM_OF_GENERATED_TESTCASES_TO_RUN_AFL = 1
FuSeBMCFuzzerLib_COVERBRANCHES_RUN2_SEEDS_NUM_MIN = 4 # minimum Number of seeds for the second run of AFL
FuSeBMCFuzzerLib_COVERBRANCHES_RUN2_SEEDS_NUM_MAX = 7 
FuSeBMCFuzzerLib_COVERBRANCHES_BYTES_PER_NUMBER = 8 


FuSeBMCFuzzerLib_COVERBRANCHES_DEFAULT_AFL_MIN_LENGTH = 36 # bytes ; you can change it ; -1: different lengths
FuSeBMCFuzzerLib_COVERBRANCHES_NUM_BYTES_TO_ADD_TO_TC = 8 # bytes to add to each testcase 
#FuSeBMCFuzzerLib_COVERBRANCHES_LOAD_EXTRAS_ENABLED = not True


FuSeBMCFuzzerLib_COVERBRANCHES_FUSEBMC_STAGE_ITERATION_INFINITE_WHILE = 100
#FuSeBMCFuzzerLib_COVERBRANCHES_FUSEBMC_STAGE_ITERATION_NON_INFINITE_WHILE = 2

# You can use clang with -fbracket-depth=100000 
FuSeBMCFuzzerLib_COVERBRANCHES_CC = AFL_HOME_PATH+ '/afl-gcc'
FuSeBMCFuzzerLib_COVERBRANCHES_CC_PARAMS = ''
FuSeBMCFuzzerLib_COVERBRANCHES_SELECTIVE_INPUTS_ENABLED = True
FuSeBMCFuzzerLib_COVERBRANCHES_SELECTIVE_INPUTS_ITERATIONS = 500
FuSeBMCFuzzerLib_COVERBRANCHES_EXTRACT_SINGLEVAL_MAXLEN_FROM_TC = True
#SF = Selective Fuzzer
FuSeBMCFuzzerLib_COVERBRANCHES_FUSEBMC_SF_STAGE_ITERATION = 3
FuSeBMCFuzzerLib_COVERBRANCHES_FUZZED_APP_TIMEOUT = '30000+' # string; millisecond;+ means tolerence
FuSeBMCFuzzerLib_COVERBRANCHES_FUZZED_APP_MEM_LIMIT = '5G' # string

FuSeBMCFuzzerLib_COVERBRANCHES_INFINITE_WHILE_TIME_INCREMENT = 10 #seconds
FuSeBMCFuzzerLib_COVERBRANCHES_SELECTIVE_INPUTS_TIME_INCREMENT = 20 #seconds

FuSeBMCFuzzerLib_TESTCASE_GEN_CC = 'gcc'
FuSeBMCFuzzerLib_TESTCASE_GEN_CC_PARAMS = ''

#FuSeBMCFuzzerLib_COVERBRANCHES_CC = 'clang'
#FuSeBMCFuzzerLib_COVERBRANCHES_CC_PARAMS = '-fbracket-depth=100000'

COVERBRANCHES_SHOW_UNIQUE_TESTCASES = not True




#goalSorting = GoalSorting.SEQUENTIAL
#goalSorting = GoalSorting.TYPE_THEN_DEPTH
goalSorting = GoalSorting.DEPTH_THEN_TYPE

goalSorting_IF_first = False # valid by DEPTH_THEN_TYPE
goalSorting_EMPTYELSE_last = True # valid by DEPTH_THEN_TYPE
goalSorting_AFTERLOOP_last = True # valid by DEPTH_THEN_TYPE
goalSorting_END_OF_FUN_last = True # valid by DEPTH_THEN_TYPE

########### PRE - RUN #####################
'''
SHOW_ME_OUTPUT = False
IS_DEBUG = False
MEM_LIMIT_BRANCHES_ESBMC = 6 # Giga
MEM_LIMIT_ERROR_CALL_ESBMC = 6 #Giga
RUN_TESTCOV = False
'''